### ISSUE TITLE
1.19.4 | Tablist doesn't showing name color 

### ISSUE THREAD

**Issue by adalmo** [Ultimating/UltraColor#11]
1.) 1.6.4

2.) Explain clearly and specifically what the problem is.
Example: When a player uses /color, and tried to use name color with any colors the name color is working on chat but on tablist it doesn't showing colors like it's just using white" Am I doing something wrong?

**Comment by Ultimating** [comment]
Could you run **/ucolor debug** and upload the ZIP file here? This will contain your UltraColor setup along with other useful info to allow me to see more clearly what setup you have so I can reproduce this issue.

Don't worry, if you're using a MySQL database for UltraColor, those details will be redacted in the ZIP file for you.

**Comment by adalmo** [comment]
[debug.zip](https://github.com/UltimateGamer200/UltraColor/files/11135763/debug.zip)

**Comment by Ultimating** [comment]
Hm, is it Better Teams you use for tablist? I'm looking at its config and I notice it uses tags that display by the player's name above their head.

Could you send the configuration for the tablist system you're using (for that, you can just copy the content to a Pastebin, make sure its exposure is at least unlisted, and attach the link to it here).

**Comment by adalmo** [comment]
https://pastebin.com/0KvpYsSM tablist config 
https://pastebin.com/MAwRzkQP tablist group config

**Comment by Ultimating** [comment]
Alright, I believe I've found the issue since I've had experience in using TAB. The issue lies in your tablist group config.

You need to set the **customtabname** for all groups (aka, `__DEFAULT__`) to be **%ucolor_colored_nickname%**. Then save the file, give TAB a reload, and the coloring should display properly (if reloading doesn't work, try rebooting). The placeholder will display the player's colored nick if they have one, otherwise, it'll just return their name colored.

Hopefully that helps :)

**Comment by adalmo** [comment]
ok thanks it works i will close this issue
