### ISSUE TITLE
1.19.4 | UltraColor 1.6.4 encountered a NullPointerException!

### ISSUE THREAD

**Issue by adalmo** [Ultimating/UltraColor#12]
To report a bug or problem with the plugin, follow the steps below:

1.) 1.6.4

2.) 1.19.3 | UltraColor 1.6.4 encountered a NullPointerException!

3.) i am not sure why this error msg is poping up

4.) Error Msg : https://pastebin.com/RXFY9Vhq

a) [debug.zip](https://github.com/UltimateGamer200/UltraColor/files/11166993/debug.zip)

**Comment by Ultimating** [comment]
Could you explain how to reproduce this bug?

From what I can see, it seems like a player of yours went into the hex color prompt, didn't type in an input when they are asked to provide a format or none, therefore causing a NullPointer.

However, from my end, I'm not seeing this issue occur, so that's why I ask if there's any steps to reproduce this bug.

**Comment by adalmo** [comment]
hmm i was checking the consol and i just found this msg from consol so yeah i am not sure how to reproduce this one

**Comment by Ultimating** [comment]
Hm, I see. Well, unfortunately, until I know how to reproduce it and see the issue on my end, I can't fix it. Because I wouldn't know 100% what triggers it and how to fix it properly.

For now, I'll close this issue, but if you end up finding out how to reproduce it, you should be able to open this back up by sending a reply with those steps to reproduce the bug.
