### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by flavioope** [Ultimating/UltraColor#2]
My suggestion is that the /ucolor setnamecolor and /ucolor setchatcolor commands are executable from the console.

1) Well, I think some of us are configurators, so if we wanted to make a menu apart from the one that the plugin already has, it would be good to be able to execute that command from the console and not just the player. (Not if I explain well)

2) Well it would affect that the plugin menu cannot be modified so it looks a bit ugly.

3) None more, I hope this is added although the plugin no longer receives updates constantly it is still a very good plugin

**Comment by Ultimating** [comment]
Hello, @flavioope!

Thank you for your suggestion! The menus are modifiable as you can modify the button item materials, menu sizes, where the buttons are, titles, etc. This doesn't mean the menus are 100% customizable, but a pretty fair (maybe a little more) amount for a free plugin. Feel free to take a look in the settings and your messages file to see what you can customize!

About your suggestion, the /ucolor setnamecolor and /ucolor setchatcolor commands were designed for players that cannot access the GUI menus but need to set their colors. That's why those commands aren't executable for the console because they were made for players. One way to possibly go about still using those commands in menus (especially if you're using plugins like EssentialsX) is to sudo the player through the console to run those commands.

If that's not possible, however, there are a couple of commands already existing that could help you.
- **/ucolor forcecolor**: This command takes in the type of color (chat/name) to apply, the username of the player to apply the color for, the color name (either a hex, rainbow, or regular), and an optional format if needed.
- **/ucolor forcegradient**:  If you need to apply gradients for players in your external menu, this command can be useful for that. The command takes in the type of gradient (chat/name), username to apply for, the first hex of gradient, the second hex of gradient, and then an optional format if needed.

Hopefully, these help you because while I understand your reasoning behind the suggestion, the commands mentioned were designed with a specific purpose and they still have that purpose.

**Comment by flavioope** [comment]
Hello, thank you very much for answering me.

I did not know that the commands that you tell me existed, thank you very much!

I will also look at the configuration thank you very much for the answer!
Excellent plugin!

**Comment by Ultimating** [comment]
Thank you and for sure! I'll go ahead and close this issue, but you should be welcome to comment to reopen it if needed.
