### ISSUE TITLE
1.16.5 | Rainbow names aren't working

### ISSUE THREAD

**Issue by ghost** [Ultimating/UltraColor#5]
Good morning! I wanted to ask you why the name rainbow of colors does not work, I use version 1.16.5 to advance and I also use chatmanager and essentials.

**Comment by Ultimating** [comment]
Hello, @mayan24!

There may be multiple causes as to why rainbow names aren't working for you. Could you please answer the following for me?
- In your Essentials config file, what do you have **change-displayname** set to?
- In your UltraColor settings file, what do you have **Name_Rainbow_Colors** set to?

Also, could you also provide your ChatManager config file, so that I could take a look at how you got your format setup? There could be the case of using the wrong placeholders, but I'm pretty confident the issue is coming from one of the two setting options I mentioned above.

May expect a delay until tomorrow afternoon my time if you respond 30-60 minutes after this message as it's almost 11 pm for me.

Thanks for opening an issue about this! :)

**Comment by ghost** [comment]
> Hola,@mayan24!
> 
> Puede haber múltiples causas por las que los nombres de arcoíris no funcionan para usted. ¿Podría por favor responderme lo siguiente?
> 
> * En su archivo de configuración de Essentials, ¿a qué tiene configurado **change-displayname** ?
> * En su archivo de configuración de UltraColor, ¿qué tiene configurado **Name_Rainbow_Colors** ?
> 
> Además, ¿podría proporcionar su archivo de configuración de ChatManager, para que pueda ver cómo configuró su formato? Podría darse el caso de usar marcadores de posición incorrectos, pero estoy bastante seguro de que el problema proviene de una de las dos opciones de configuración que mencioné anteriormente.
> 
> Puede esperar un retraso hasta mañana por la tarde mi hora si responde 30-60 minutos después de este mensaje, ya que son casi las 11 p. m. para mí.
> 
> ¡Gracias por abrir un tema sobre esto! :)

Hi @UltimateGamer200!

I'll explain you how I have configured the things you asked for:
1. The Essentials option (change-displayname) is set to FALSE.
2. In ultra color (Name_Rainbow_Colors) I have it set to TRUE
3. And this is the configuration file of my ChatManager: https://pastebin.com/VuQw2kq9

**Comment by Ultimating** [comment]
Thank you @mayan24!

I did some editing in the ChatManager config you provided. You were using {player} instead of {displayname}.

I've attached the edited file [here](https://pastebin.com/xWukdkiK), so you should only need to do the following:

- First, take a backup of the ChatManager config file you have right now on your server. 
- Then, go inside your ChatManager config, select all the text content, and replace it with the content on the Pastebin.
- Finally, save the file and reload ChatManager. It should now be working (I just tested on 1.16.5 and it seems to be fine). If reloading doesn't work, reboot the server, and if that doesn't work, please let me know.

**Comment by ghost** [comment]
> Gracias@mayan24!
> 
> Hice algunas ediciones en la configuración de ChatManager que proporcionaste. Estabas usando {player} en lugar de {displayname}.
> 
> He adjuntado el archivo editado [aquí](https://pastebin.com/xWukdkiK) , por lo que solo debe hacer lo siguiente:
> 
> * Primero, haga una copia de seguridad del archivo de configuración de ChatManager que tiene ahora mismo en su servidor.
> * Luego, ingrese a su configuración de ChatManager, seleccione todo el contenido de texto y reemplácelo con el contenido en el Pastebin.
> * Finalmente, guarde el archivo y vuelva a cargar ChatManager. Ahora debería estar funcionando (acabo de probar en 1.16.5 y parece estar bien). Si la recarga no funciona, reinicie el servidor, y si eso no funciona, hágamelo saber.

@UltimateGamer200  Thank you very much! again I emphasize very good complement and excellent support my friend.

**Comment by UltimateGamer200** [comment]
Of course, happy to have helped! If all is resolved, feel free to close the issue, or I can do so for you.

**Comment by Ultimating** [comment]
@mayan24 Of course, happy to have helped! If all is resolved, feel free to close the issue, or I can do so for you.
