### ISSUE TITLE
More gradient color options

### ISSUE THREAD

**Issue by OdontoZoom** [Ultimating/UltraColor#9]
**Maybe, you can set between 1 - 3 RGB (Hex Format) color. People could combine more colors to show only in names.**
Let's see an example:

When you set HEX values, you only can set max 2 colors:
![image](https://user-images.githubusercontent.com/87169363/221012175-b3189417-fe6e-470f-a8a8-4e69c9692bfd.png)

So the name would look like this:

![image](https://user-images.githubusercontent.com/87169363/221012720-056ad427-861a-4157-ab0d-2112a85f4875.png)

But, if you could add only 1 more option, to add Hex color, like this:

![image](https://user-images.githubusercontent.com/87169363/221013067-a57351ae-731d-434c-85e6-3aaacf228494.png)

It would give more combinations to show.

![image](https://user-images.githubusercontent.com/87169363/221013280-2c41571d-79fe-4a9b-ad5c-a3311510e891.png)

![image](https://user-images.githubusercontent.com/87169363/221013391-2f2da247-0e7e-4f15-a5ea-b0c7ab228b62.png)

![image](https://user-images.githubusercontent.com/87169363/221013480-60928d48-6668-45f3-a202-98a51da0cca5.png)

That would nice for players and allows us to create better and creative rewards.

This not affect my server, but would enhance any server where the plugin is installed.

Thank you. If it's not possible, it's ok.

(Sorry, I don't speak english. Hope you can understand what I mean)

**Comment by Ultimating** [comment]
Hello!

Before I discontinued UltraColor last March, I was given the idea to provide three-colored gradients. I tried to implement this back over a year ago but was unsuccessful. I know it's possible, but I just haven't found a solution, so it's just been in limbo since the last time I tried it. I may give it another try this time around because who knows, maybe I can find something.
